### ISSUE TITLE
Error in Add new Author

### ISSUE THREAD

**Issue by jjgonver** [tarlepp/angular-sailsjs-boilerplate#113]
````
error: Sending 500 ("Server Error") response:
 Error (E_UNKNOWN) :: Encountered an unexpected error
error: la sintaxis de entrada no es válida para integer: «»
    at Connection.parseE (C:\Users\user\app\backend\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (C:\Users\user\app\backend\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (C:\Users\user\app\backend\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:525:20)

Details:  error: la sintaxis de entrada no es válida para integer: «»
````
Thanks

**Comment by tarlepp** [comment]
Hmm could you provide more information about this? I tried to add new author and there was no errors.

Sails verbose log:
```
verbose: Receiving incoming message from Socket.io:  { method: 'post',
  headers:
  { Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json;charset=utf-8',
    authorization: 'Bearer ****removed token****' },
  data:
  { name: 'foobar',
    description: 'barfoo',
    token: '****removed token****' },
  url: 'http://wunder.sytes.net:1339/author' }
verbose: Interpreting socket.io message as virtual request to "post http://wunder.sytes.net:1339/author"...
  verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/policies/authenticated.js:17 [Policy.Authenticated() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Token.js:55 [Service.Token.getToken() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Token.js:35 [Service.Token.verify() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/policies/isAdmin.js:13 [Policy.isAdmin() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/policies/addDataCreate.js:11 [Policy.addDataCreate() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Logger.js:68 [Service.Logger.request() called]
verbose: Receiving incoming message from Socket.io:  { method: 'get',
  headers:
  { Accept: 'application/json, text/plain, */*',
    authorization: 'Bearer ****removed token****' },
  data: { token: '****removed token****' },
  url: 'http://wunder.sytes.net:1339/author?limit=10&populate=books&sort=name+ASC' }
verbose: Interpreting socket.io message as virtual request to "get http://wunder.sytes.net:1339/author?limit=10&populate=books&sort=name+ASC"...
  verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/policies/authenticated.js:17 [Policy.Authenticated() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Token.js:55 [Service.Token.getToken() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Token.js:35 [Service.Token.verify() called]
verbose: Receiving incoming message from Socket.io:  { method: 'get',
  headers:
  { Accept: 'application/json, text/plain, */*',
    authorization: 'Bearer ****removed token****' },
  data: { token: '****removed token****' },
  url: 'http://wunder.sytes.net:1339/author/count/' }
verbose: Interpreting socket.io message as virtual request to "get http://wunder.sytes.net:1339/author/count/"...
  verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/policies/authenticated.js:17 [Policy.Authenticated() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Token.js:55 [Service.Token.getToken() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Token.js:35 [Service.Token.verify() called]
verbose: Receiving incoming message from Socket.io:  { method: 'get',
  headers:
  { Accept: 'application/json, text/plain, */*',
    authorization: 'Bearer ****removed token****' },
  data: { token: '****removed token****' },
  url: 'http://wunder.sytes.net:1339/author/6' }
verbose: Interpreting socket.io message as virtual request to "get http://wunder.sytes.net:1339/author/6"...
  verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/policies/authenticated.js:17 [Policy.Authenticated() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Token.js:55 [Service.Token.getToken() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Token.js:35 [Service.Token.verify() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Logger.js:68 [Service.Logger.request() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Logger.js:68 [Service.Logger.request() called]
verbose: Receiving incoming message from Socket.io:  { method: 'get',
  headers:
  { Accept: 'application/json, text/plain, */*',
    authorization: 'Bearer ****removed token****' },
  data: { token: '****removed token****' },
  url: 'http://wunder.sytes.net:1339/book?author=6' }
verbose: Interpreting socket.io message as virtual request to "get http://wunder.sytes.net:1339/book?author=6"...
  verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/policies/authenticated.js:17 [Policy.Authenticated() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Token.js:55 [Service.Token.getToken() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Token.js:35 [Service.Token.verify() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Logger.js:68 [Service.Logger.request() called]
verbose: Receiving incoming message from Socket.io:  { method: 'get',
  headers:
  { Accept: 'application/json, text/plain, */*',
    authorization: 'Bearer ****removed token****' },
  data: { token: '****removed token****' },
  url: 'http://wunder.sytes.net:1339/book/count/?author=6' }
verbose: Interpreting socket.io message as virtual request to "get http://wunder.sytes.net:1339/book/count/?author=6"...
  verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/policies/authenticated.js:17 [Policy.Authenticated() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Token.js:55 [Service.Token.getToken() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Token.js:35 [Service.Token.verify() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Logger.js:68 [Service.Logger.request() called]
verbose: /home/wunder/projects/angular-sailsjs-boilerplate-backend/api/services/Logger.js:68 [Service.Logger.request() called]
```

**Comment by jjgonver** [comment]
Well. It occur when I click in the 'Add new Author' button. After that appear 2 error 'E_UNKNOWN' messages in the navigator window and it show the Authors form. Then I can fill the form and save the data. Meanwhile, in the backend console show the next message:

````
error: Sending 500 ("Server Error") response:
 Error (E_UNKNOWN) :: Encountered an unexpected error
error: la sintaxis de entrada no es válida para integer: «»
    at Connection.parseE (C:\Users\user\app\backend\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (C:\Users\user\app\backend\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (C:\Users\user\app\backend\node_modules\sails-postgresql\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:525:20)

Details:  error: la sintaxis de entrada no es válida para integer: «»
````

And I can not find the sails verbose log.

Thanks
I love this boilerplate!

**Comment by tarlepp** [comment]
Can't really say what is happening on your env. Tried to make that error to happen with chrome, firefox, opera and ie (all in latest versions) and I didn't get any errors...

**Comment by jjgonver** [comment]
Where is the log file?
I can't find it

**Comment by tarlepp** [comment]
That's just basic sails lo, see:
http://sailsjs.org/documentation/concepts/logging/sails-log 
http://sailsjs.org/documentation/reference/configuration/sails-config-log

**Comment by jjgonver** [comment]
Ok, thank you. I'm sorry but I'm very novice.

**Comment by jjgonver** [comment]
I start from 0. And I have found that with 'sails-disk' adapter this error does not occur. It appear when I change the adapter to my local postgresql.

**Comment by tarlepp** [comment]
I have tried that with sails-disk, sails-memory and sails-mysql adapters without any errors. So this seems like to be adapter specified issue and nothing really to do with this project.
