### ISSUE TITLE
Error to try 'sails lift'

### ISSUE THREAD

**Issue by jjgonver** [tarlepp/angular-sailsjs-boilerplate#121]
At this moment, I have this boilerplate works ok on my PC but I'm trying to move to another PC. In this new PC when I try to make 'sails lift':
````
info: Starting app...

error: Error: The hook `orm` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.orm._hookTimeout to a higher value (currently 20000)
    at tooLong [as _onTimeout] (C:\Users\user\app\backend\node_modules\sails\lib\app\private\loadHooks.js:92:21)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

C:\Users\user\app\backend>sails lift

info: Starting app...

error: A hook (`load-db`) failed to load!
C:\Users\user\app\backend\node_modules\sails-mysql\lib\adapter.js:58
      if (evName === 'error') { throw data; }
                                ^

AdapterError: Invalid connection name specified
    at getConnectionObject (C:\Users\user\app\backend\node_modules\sails-mysql\lib\adapter.js:1211:35)
    at spawnConnection (C:\Users\user\app\backend\node_modules\sails-mysql\lib\adapter.js:1126:7)
    at Object.module.exports.adapter.destroy (C:\Users\user\app\backend\node_modules\sails-mysql\lib\adapter.js:1054:16)
    at module.exports.destroy (C:\Users\user\app\backend\node_modules\waterline\lib\waterline\adapter\dql.js:272:13)
    at C:\Users\user\app\backend\node_modules\waterline\lib\waterline\query\dql\destroy.js:61:18
    at C:\Users\user\app\backend\node_modules\waterline\node_modules\async\lib\async.js:49:16
    at C:\Users\user\app\backend\node_modules\waterline\node_modules\async\lib\async.js:263:32
    at C:\Users\user\app\backend\node_modules\waterline\node_modules\async\lib\async.js:40:16
    at bound.<anonymous> (C:\Users\user\app\backend\node_modules\waterline\lib\waterline\utils\schema.js:151:44)
    at fn (C:\Users\user\app\backend\node_modules\waterline\lib\waterline\utils\callbacksRunner.js:117:10)
    at C:\Users\user\app\backend\node_modules\waterline\node_modules\async\lib\async.js:162:20
    at iterate (C:\Users\user\app\backend\node_modules\waterline\node_modules\async\lib\async.js:256:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (C:\Users\user\app\backend\node_modules\waterline\node_modules\async\lib\async.js:275:9)
    at Object.async.forEachSeries.async.eachSeries (C:\Users\user\app\backend\node_modules\waterline\node_modules\async\lib\async.js:211:22)
    at Object.runner.beforeDestroy (C:\Users\user\app\backend\node_modules\waterline\lib\waterline\utils\callbacksRunner.js:120:9)
    at bound.module.exports [as destroy] (C:\Users\user\app\backend\node_modules\waterline\lib\waterline\query\dql\destroy.js:54:13)
    at bound [as destroy] (C:\Users\user\app\backend\node_modules\sails\node_modules\lodash\dist\lodash.js:729:21)
    at Deferred.exec (C:\Users\user\app\backend\node_modules\waterline\lib\waterline\query\deferred.js:477:16)
    at C:\Users\user\app\backend\node_modules\barrels\index.js:132:23
    at C:\Users\user\app\backend\node_modules\async\lib\async.js:181:20
    at Object.async.forEachOf.async.eachOf (C:\Users\user\app\backend\node_modules\async\lib\async.js:233:13)
    at Object.async.forEach.async.each (C:\Users\user\app\backend\node_modules\async\lib\async.js:209:22)
````
I have noticed that the tables have been created in the database but without data.
Thanks in advance.

**Comment by markmssd** [comment]
This [issue](https://github.com/balderdashy/sails-mysql/issues/158) might help you, he's getting the same error as you.

Another thing you can try is extend the hookTimeout time, to give more time to the ORM to populate your DB. e.g. in your local.js file, add ``` hookTimeout: 120000 ```. Note that this is in milliseconds, so 120000 = 2 minutes...

Hope that helps.

**Comment by jjgonver** [comment]
I just resolve it.

Probably is a problem with Windows 10 Pro and node-gyp.

From a clean windows 10 installation this is the step that I follow to start with this boilerplate:
1. Install Git-2.7.4-64-bit from https://git-scm.com/
2. Install Python-2.7.11 from https://www.python.org/downloads/ and add to the PATH (v3.x.x is not supported)
3. Install node-v5.9.0-x64 from https://nodejs.org/en/
4. Update npm to the last version: npm install npm -g
5. Install Rubyinstaller-2.2.4 32bit from http://rubyinstaller.org/
6. gem install scss_lint
7. Install Visual Studio 2015 community edition with Common Tools for Visual C++ selected from https://www.visualstudio.com/
8. Install node-gyp: npm install -g node-gyp
9. npm config set python python2.7
10. npm config set msvs_version 2015
11. Install mysql-installer-community-5.7.11.0 from http://dev.mysql.com/downloads/installer/
12.npm install sails -g
13.npm install gulp -g
14.npm install bower -g

Thanks for your answer

**Comment by tarlepp** [comment]
Good to hear that this one is resolved, going to close this one now.
