### ISSUE TITLE
Cannot read property 'parseSignedCookie' of undefined

### ISSUE THREAD

**Issue by wangxuq** [tarlepp/angular-sailsjs-boilerplate#63]
下边的这个问题是如何解决的呢？
<pre>
var parseSignedCookie = require('connect').utils.parseSignedCookie;
                                                ^
TypeError: Cannot read property 'parseSignedCookie' of undefined
    at Object.<anonymous> (E:\nodejs\lianxi\chat\app.js:14:49)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
</pre>

**Comment by tarlepp** [comment]
Hmm, sorry can't understand that language :( If you still have some problems please make issue using english.

**Comment by wangxuq** [comment]
oh sorry,that's chinese.I have fixed that problem.thanks.
