### ISSUE TITLE
there are something wrong with historyApiFallback

### ISSUE THREAD

**Issue by Almax** [tarlepp/angular-sailsjs-boilerplate#74]
`TypeError: Cannot read property 'indexOf' of undefined
  at historyApiFallback (c:\gitroot\angsails\frontend\node_modules\connect-history-api-fallback\lib\index.js:19:28)
  at Object.gulp.task.g.serve.middleware [as handle] (c:\gitroot\angsails\frontend\gulpfile.js:190:12)
  at next (c:\gitroot\angsails\frontend\node_modules\gulp-serve\node_modules\connect\lib\proto.js:193:15)
  at Function.app.handle (c:\gitroot\angsails\frontend\node_modules\gulp-serve\node_modules\connect\lib\proto.js:201:3)
  at Server.app (c:\gitroot\angsails\frontend\node_modules\gulp-serve\node_modules\connect\lib\connect.js:65:37)
  at Server.emit (events.js:110:17)
  at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:491:12)
  at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
  at Socket.socketOnData (_http_server.js:343:22)
  at Socket.emit (events.js:107:17)
  at readableAddChunk (_stream_readable.js:163:16)
  at Socket.Readable.push (_stream_readable.js:126:10)
  at TCP.onread (net.js:538:20)`

**Comment by LeonardoGentile** [comment]
Try to add this under `dependencies` inside the `backend/packages.json`: `"connect-history-api-fallback": "0.0.5"`

**Comment by tarlepp** [comment]
@Almax yeah, that error occurs sometime, but it won't crash the server. @LeonardoGentile so newer version fixes that?

**Comment by gpapin** [comment]
Same error here, @LeonardoGentile installing this dependency didn't solved it.

**Comment by tarlepp** [comment]
I need to check all those dependencies and try to update those to "latest" version and see if that fixes this.

**Comment by markmssd** [comment]
I used to have that error too.
I have upgraded all dependencies of the backend, and most of the frontend, and it fixed that issue.

**Comment by tarlepp** [comment]
Hmm, I think that this problem is solved atm. Closing this one for now.
