### ISSUE TITLE
Promise issue, seems on the server side

### ISSUE THREAD

**Issue by Almax** [tarlepp/angular-sailsjs-boilerplate#75]
in the browser console:
`LoginHistoryModel.statistics() failed. Object {data: Object, status: 500, config: Object, statusText: undefined} userlogin Browser
LoginHistoryModel.statistics() failed. Object {data: Object, status: 500, config: Object, statusText: undefined} userlogin Os
LoginHistoryModel.statistics() failed. Object {data: Object, status: 500, config: Object, statusText: undefined} userlogin User`

node console
response.negotiate(error) Output
```
 TypeError: undefined is not a function
    at Aggregate.sum (c:\gitroot\angsails\backend\node_modules\sails-disk\lib\aggregates.js:109:7)
    at new module.exports (c:\gitroot\angsails\backend\node_modules\sails-disk\lib\aggregates.js:38:24)
    at Database.select (c:\gitroot\angsails\backend\node_modules\sails-disk\lib\database.js:312:19)
    at Object.module.exports.adapter.find (c:\gitroot\angsails\backend\node_modules\sails-disk\lib\adapter.js:86:28)
    at module.exports.find (c:\gitroot\angsails\backend\node_modules\sails\node_modules\waterline\lib\waterline\adapter\dql.js:120:13)
    at _runOperation (c:\gitroot\angsails\backend\node_modules\sails\node_modules\waterline\lib\waterline\query\finders\operations.js:408:29)
    at run (c:\gitroot\angsails\backend\node_modules\sails\node_modules\waterline\lib\waterline\query\finders\operations.js:69:8)
    at bound.module.exports.find (c:\gitroot\angsails\backend\node_modules\sails\node_modules\waterline\lib\waterline\query\finders\basic.js:245:16)
    at bound [as find] (c:\gitroot\angsails\backend\node_modules\sails\node_modules\lodash\dist\lodash.js:729:21)
    at Deferred.exec (c:\gitroot\angsails\backend\node_modules\sails\node_modules\waterline\lib\waterline\query\deferred.js:501:16)
    at tryCatcher (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\util.js:24:31)
    at ret (eval at <anonymous> (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\promisify.js:155:12), <anonymous>:13:39)
    at Deferred.toPromise (c:\gitroot\angsails\backend\node_modules\sails\node_modules\waterline\lib\waterline\query\deferred.js:510:61)
    at Deferred.then (c:\gitroot\angsails\backend\node_modules\sails\node_modules\waterline\lib\waterline\query\deferred.js:521:15)
    at tryCatcher (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\util.js:24:31)
    at doThenable (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\thenables.js:52:38) 
```

console.error Output:
```
[TypeError: undefined is not a function]
Unhandled rejection TypeError: undefined is not a function
    at handlerError (c:\gitroot\angsails\backend\api\controllers\UserLoginController.js:100:15)
    at tryCatcher (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromises (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\async.js:182:16)
    at Async._drainQueues (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\async.js:192:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
Unhandled rejection TypeError: undefined is not a function
    at handlerError (c:\gitroot\angsails\backend\api\controllers\UserLoginController.js:100:15)
    at tryCatcher (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromises (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\async.js:182:16)
    at Async._drainQueues (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\async.js:192:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
Unhandled rejection TypeError: undefined is not a function
    at handlerError (c:\gitroot\angsails\backend\api\controllers\UserLoginController.js:100:15)
    at tryCatcher (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\util.js:24:31)
    at Promise._settlePromiseFromHandler (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\promise.js:454:31)
    at Promise._settlePromiseAt (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\promise.js:530:18)
    at Promise._settlePromises (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\promise.js:646:14)
    at Async._drainQueue (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\async.js:182:16)
    at Async._drainQueues (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\async.js:192:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\gitroot\angsails\backend\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by tarlepp** [comment]
Hmm, this could be ```sails-disk``` adapter related issue. Could you try with different adapter, personally I have used ```sails-mysql``` adapter on the app.

**Comment by tarlepp** [comment]
I'm still waiting for answer from you @Almax ?

**Comment by markmssd** [comment]
I had this issue too, which was indeed related to ```sails-disk```. With ```sails-mysql```, I confirm that there was no problem at all.
